trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
- group: MyAzureARMVars

steps:
# 1 Checkout
- checkout: self

# 2 Azure Login
- task: AzureCLI@2
  displayName: 'Azure Login'
  inputs:
    azureSubscription: 'my-sp-connection'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      Write-Host "âœ” Azure login successful"

# 3 Install Terraform
- powershell: |
      Invoke-WebRequest https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_windows_amd64.zip -OutFile terraform.zip
      Expand-Archive terraform.zip -DestinationPath "$env:AGENT_TEMPDIRECTORY\terraform"
      Move-Item "$env:AGENT_TEMPDIRECTORY\terraform\terraform.exe" "C:\windows\system32\terraform.exe" -Force
      terraform -version
  displayName: 'Install Terraform'

# 4 Terraform Init
- powershell: |
      terraform init -reconfigure
  displayName: 'Terraform Init'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

# 5 Plan
- powershell: |
      terraform plan -var="admin_password=$(admin_password)"
  displayName: 'Terraform Plan'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

# 6 Apply
- powershell: |
      terraform apply -auto-approve -var="admin_password=$(admin_password)"
  displayName: 'Terraform Apply'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)









