trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:

# Checkout
- checkout: self

# Login
- task: AzureCLI@2
  displayName: 'Azure Login'
  inputs:
    azureSubscription: 'azure-spn-secret'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      Write-Host "âœ” Azure login successful"

# Install Terraform
- powershell: |
      Invoke-WebRequest https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_windows_amd64.zip -OutFile terraform.zip
      Expand-Archive terraform.zip -DestinationPath "$env:AGENT_TEMPDIRECTORY\terraform"
      Move-Item "$env:AGENT_TEMPDIRECTORY\terraform\terraform.exe" "C:\windows\system32\terraform.exe" -Force
      terraform -version
  displayName: 'Install Terraform'

# Terraform Init
- powershell: |
      terraform init -reconfigure
  displayName: 'Terraform Init'

# Terraform Plan
- powershell: |
      terraform plan -var="admin_password=$(admin_password)"
  displayName: 'Terraform Plan'

# Terraform Apply
- powershell: |
      terraform apply -auto-approve -var="admin_password=$(admin_password)"
  displayName: 'Terraform Apply'










